CREATE DATABASE AlComBank
GO
USE AlComBank
GO

CREATE TABLE Account (
	AccountId INT PRIMARY KEY IDENTITY(1, 1),
	Balance FLOAT NOT NULL DEFAULT(0),
	CardNumber CHAR(16),
	CardExpireDate CHAR(4)
)

CREATE TABLE User_ (
	UserId INT PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	Password NVARCHAR(255) NOT NULL,
	AccountId INT FOREIGN KEY(AccountId) REFERENCES Account(AccountId)
)