CREATE DATABASE AlComBank
GO
USE AlComBank
GO

CREATE TABLE Credit (
	IdCredit INT PRIMARY KEY IDENTITY(1, 1),
	SumaCredit INT NOT NULL,
	PerioadaCreditare INT NOT NULL,
	RataAnualaCredit INT NOT NULL,
	DataAcreditarii DATE
)

CREATE TABLE Account (
	AccountId INT PRIMARY KEY IDENTITY(1, 1),
	Balance FLOAT NOT NULL DEFAULT(0),
	CardNumber CHAR(16),
	CardExpireDate CHAR(4),
	IdCredit INT FOREIGN KEY(IdCredit) REFERENCES Credit(IdCredit)
)

CREATE TABLE User_ (
	UserId INT PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(255) NOT NULL,
	Email NVARCHAR(255) NOT NULL UNIQUE,
	Password NVARCHAR(255) NOT NULL,
	AccountId INT FOREIGN KEY(AccountId) REFERENCES Account(AccountId)
)